### ISSUE TITLE
taskset not found

### ISSUE THREAD

**Issue by pedrofale** [raphael-group/chisel#11]
Hi,

I'm getting this error when using the `chisel-calling` command: `sh: taskset: command not found`. This is a Linux command, and I'm trying to run CHISEL on MacOS. Are there any workarounds?

Here is the full log:
```
[2020-Aug-25 19:03:55]Parsing and checking arguments
[2020-Aug-25 19:03:55]Arguments:
        significativity : 0.02
        sensitivity : 1.0
        seed : None
        input : here.tsv
        LB : 0
        scoring : False
        e : 0.05
        shift : 0.05

        maxploidy : 4
        j : 4
        fastscaling : False
        restarts : 200
        lord : 1
        UB : 100
[2020-Aug-25 19:03:55]Reading combined RDRs and BAFs of barcoded cells
[2020-Aug-25 19:04:42]Formatting RDRs and BAFs
[2020-Aug-25 19:05:43]Clustering globally
sh: taskset: command not found
```

**Comment by simozacca** [comment]
Thank you for your interest in CHISEL!

The message that you see should only be considered a warning and it is not an error on MacOS; the behavior of CHISEL is not affected at all and CHISEL properly runs on MacOS. CHISEL has been deeply tested on MacOS, so everything should work fine. Please ignore the message.

In the next version, we will remove that message and command when running on MacOS.
