### ISSUE TITLE
No return in Call.py and AssertionError: There is a bin with a BAF shift > 0.5, likely BAF was not mirrored between 0 and 0.5

### ISSUE THREAD

**Issue by Rongtingting** [raphael-group/chisel#16]
Hi Chisel developers,

Thank you for developing this tool! After I tried the demo successfully, I'm very excited to try it out on my data. The version of CHISEL is 0.0.4 installed via conda. As described in the detailed tutorial, there are 4 input files:
- A single-cell barcoded BAM
- reference human genome
- a matched-normal BAM (GENERATED via chisel-pseudonormal)
- A vcf file with phased germline SNPs(for saving time in the test, I just use the chr8 VCF)

Yet, chisel didn't complete it's procedure. While the error message displayed in log 
`AssertionError: There is a bin with a BAF shift > 0.5, likely BAF was not mirrored between 0 and 0.5`

But I think there are no BAF shift > 0.5 in my output data.

Here I attach the log files or other related info:
[chisel_GX109_chr8_hg38_out_20201009.log](https://github.com/raphael-group/chisel/files/5498603/chisel_GX109_chr8_hg38_out_20201009.log)
[combo_chr8_head20.txt](https://github.com/raphael-group/chisel/files/5498609/combo_chr8_head20.txt)

[normal_bam_head10.txt](https://github.com/raphael-group/chisel/files/5498607/normal_bam_head10.txt)
[possorted_bam_head10.txt](https://github.com/raphael-group/chisel/files/5498612/possorted_bam_head10.txt)
[phased_GX109_hg38_chr8_head10.txt](https://github.com/raphael-group/chisel/files/5498615/phased_GX109_hg38_chr8_head10.txt)

I think maybe the reason is that there is no return in my try
https://github.com/raphael-group/chisel/blob/master/src/Caller.py#L324
But I can not find out why there is no return. Could you give me some instructions on how to figure it out?
Thanks a lot for your time!!!

**Comment by simozacca** [comment]
Thank you for the interest in CHISEL! I will be glad to help you with this issue. 

At first glance, the problem might be the presence of a cell without sequencing reads in chromosome 8. In fact, this can happen because CHISEL has been ran on all autosomes (the default value for `-c`) but SNPs are provided only for chr8, meaning that only genomic bins in chromosome 8 will be retained (does the combo file only contains chr8 bins?). However, there might be other issues that we would like to investigate, could you please share with me your combo file `combo/combo.tsv`? If you prefer to do it through email, please use the email address [here](https://www.ucl.ac.uk/cancer/zaccaria-lab).

Also, as an additional test, could you please try to run your CHISEL command by adding the flag `-c chr8`?

**Comment by Rongtingting** [comment]
Thank you for your help! I have tried to add the flag -c chr8 and it works!

And I wonder if there is  a separated chisel cmd to just combine the calculated RDR and BAF, like `chisel-calling` can run from the intermediate files directly.

**Comment by Rongtingting** [comment]
Thank you for your help! I think the problem has been solved!

**Comment by simozacca** [comment]
> Thank you for your help! I have tried to add the flag -c chr8 and it works!
> 
> And I wonder if there is a separated chisel cmd to just combine the calculated RDR and BAF, like `chisel-calling` can run from the intermediate files directly.

While there is yet no exposed CHISEL command to do that, there is indeed an easy ways in the CHISEL repository to do that; this cannot be used directly through the conda installation but you need to clone the repository and use the corresponding programs directly. In details:

You can use `bin/Combiner.py` (just call the command as `python2 bin/Combiner.py` while having the `chisel` conda environment activated) to compute the RDR and BAF file, i.e. `combo/combo.tsv`, from two inputs: (1) the read count file `rdr/rdr.tsv`, and (2) the phased SNP read count file `baf/baf.tsv`. Please run `bin/Combiner.py -h` for details of the interface and please find [here](https://github.com/raphael-group/chisel/blob/master/doc/chisel.md) the details of all formats.

More details about this possibility are also reported in https://github.com/raphael-group/chisel/issues/10#issuecomment-680212471

**Comment by Rongtingting** [comment]
> > Thank you for your help! I have tried to add the flag -c chr8 and it works!
> > And I wonder if there is a separated chisel cmd to just combine the calculated RDR and BAF, like `chisel-calling` can run from the intermediate files directly.
> 
> While there is yet no exposed CHISEL command to do that, there is indeed an easy ways in the CHISEL repository to do that; this cannot be used directly through the conda installation but you need to clone the repository and use the corresponding programs directly. In details:
> 
> You can use `bin/Combiner.py` (just call the command as `python2 bin/Combiner.py` while having the `chisel` conda environment activated) to compute the RDR and BAF file, i.e. `combo/combo.tsv`, from two inputs: (1) the read count file `rdr/rdr.tsv`, and (2) the phased SNP read count file `baf/baf.tsv`. Please run `bin/Combiner.py -h` for details of the interface and please find [here](https://github.com/raphael-group/chisel/blob/master/doc/chisel.md) the details of all formats.
> 
> More details about this possibility are also reported in [#10 (comment)](https://github.com/raphael-group/chisel/issues/10#issuecomment-680212471)

Thanks a lot! I tried `python2.7 bin/Combiner.py` directly yesterday and it works!
