### ISSUE TITLE
Question about VCF file

### ISSUE THREAD

**Issue by Romeo1-1** [raphael-group/chisel#24]
Hello, thank you very much for this package !

I have 2 questions about the package. Just to give some context, i'm comparing samples of sorted cancerous cells from one patient, before and after treatment.

1) I don't have "matched normal samples" available, but i know that there is some "contamination" from normal cells. When using the command "pseudo-normal", i get some cells (around 20 per sample) which is good. 

I then followed your advices to call germline SNPs in this pseudo-normal bam file but it's very very very time consuming and requires lots of input on my side . First, BCFtools only recognize the "pseudo-normal" as 1 cell, meaning i need to split first the pseudo-normal bam files into bam files containing only one cell each. Then, because my samples were aligned on hg38, I have to do the "lay over" part. 

[I was able to find this online platform that does the liftover automatically](https://hybridcomputing.ikmb.uni-kiel.de/webservice/sites/submitjob.php?mode=imputation). It saves some times but I need to first split my VCF file into 1 VCF file for each chromosome then merge the results. 

In the end, I spent way more time pre-processing my data than working on your package and I'm not entirely sure of the "quality" of the call because I only get a few cells (around 20) per sample. Later I would need to do that for more patients, possibly a dozen. 

In that case, do you have any advice on how to create a VCF file with less steps, please ? And even if you do not recommend it, would it be possible to use a phased vcf file from dbSNP for example ? That would save me countless hours.

2) I'm comparing 2 samples from 1 patient and I would like to see if there is any new copy number alteration after treatment. If i'm not misunderstood, there's no possibility to directly compare 2 samples with CHISEL, right ? Do you think it could work if I merge the 2 .bam files in 1 "big" bam file and then do the analyse on it ?

Thank you a lot in advance,

Remi Tilmont

**Comment by simozacca** [comment]
Thank you for you question. I would have two reccomendations:

1. If you have a barcoded BAM file where cells have been barcoeded through `RG` flags (as done for example by `chisel_prep`) then you should use the BCFtools command `mpileup` with the flag `--ignore-RG` to genotype SNPs and to consider all cells together, avoiding to consider every cell independently.

2. If you do not have a matched-normal bulk sample, I would reccommend to use the new nonormal command of CHISEL, which does not require any matched normal sample (still requires phased SNPs though). If you install the most-updated version of CHISEL, you should be able to read the details of the command by running `chisel_nonormal -h`. Also, the interface of the command should be the same as the default chisel command but you simply do not input any matched normal sample.
