### ISSUE TITLE
Questions about single-cell barcoded BAM, PREFIX and the "CB:Z:" tag

### ISSUE THREAD

**Issue by zhaoxiaofei** [raphael-group/chisel#29]
Hi chisel-devs,

I have a question about the single-cell barcoded BAM file which is the main input to chisel: what if the raw data do not contain any barcode information? For examples, in the sequencing data with accession SRA018951.105, different cells simply have different FASTQ filenames. In this case, can I just fill in dummy barcode into the FASTQ or BAM files? 

Best,
Xiaofei

**Comment by simozacca** [comment]
Yes, dummy barcodes can be used (they just need to be unique identifiers for each cell), and we reccomend the use of `chisel-prep` command that does this processing automatically for you.
