### ISSUE TITLE
How to form pseudo match-normal sample?

### ISSUE THREAD

**Issue by ivanov-v-v** [raphael-group/chisel#3]
In section `Usage` of your guide, it's mentioned, that:
 

> "A matched-normal BAM file containing sequencing reads from a matched-normal sample from the same patient. When this sample is not available, a user can use the corresponding CHISEL command to form a **pseudo** matched-normal sample by extracting diploid normal cells. Note that this approach is successful only when normal diploid cells are present in the barcoded BAM file." 

Nevertheless, I am unable to find figure out how to form a **pseudo** match-normal sample neither from demos nor from the code. Is this functionality implemented?

**Comment by simozacca** [comment]
Thank you for pointing out this issue! The repository is indeed erroneously missing the corresponding command to form a pseudo matched-normal sample. We will soon fix the issue by bringing back the missing command with the next stable release, which is expected to happen in the next week or so.

I will keep the issue open until the missing command will be re-integrated.

**Comment by ivanov-v-v** [comment]
That would be really appreciated!

We know for sure that there are normal cells in our sample, we even know, which ones, but splitting those BAM-files into pieces... That's quite unpleasant, especially given the fact the 10x Genomics doesn't provide a convenient tool to filter BAM by the list of barcodes. 

Looking forward to the next release then!

**Comment by simozacca** [comment]
The command to form a pseudo matched-normal sample as well as a related demo are now available.
