### ISSUE TITLE
Other species

### ISSUE THREAD

**Issue by benhedan** [raphael-group/chisel#37]
Hi

Is it possible to use Chisel for an other species than human?

Best regards

Benoit

**Comment by simozacca** [comment]
CHISEL does not directly require the analysed cells to be human (expect requiring to have 2 haplotypes), but the required SNP phasing can be more problematic for other species; in particular, you cannot use the reccommended reference-based phasing for other species.

So, if you find a way to obtain SNP phasing for your species, yes you can use CHISEL on your cells.

Please feel free to re-open the issue if you have other related questions
