### ISSUE TITLE
Hardcoded list of chromosomes

### ISSUE THREAD

**Issue by ivanov-v-v** [raphael-group/chisel#4]
Seems like you are [not forwarding](https://github.com/raphael-group/chisel/blob/05e75cff342086899ac3cc396e359cabc2bb152d/bin/chisel.py#L124) a list of chromosomes to the `RDREstimator.py`, despite the fact that you [allow](https://github.com/raphael-group/chisel/blob/05e75cff342086899ac3cc396e359cabc2bb152d/bin/chisel.py#L23) passing those to the `chisel.py`. This causes a lot of confusion because it's not always `chr1 ... chr22` in 10x BAMs and the script fails to detect any cells due to that. I can make a pull request that fixes this issue if you don't mind

**Comment by simozacca** [comment]
Thank you for this very useful feedback and for pointing out an actual bug: the list of chromosomes should be indeed forwarded to `RDREstimator.py`. Please feel free to initiate a pull request and I will be very happy to review it. 

In the coming version the chromosome names, as well as the chromosome lengths will be read directly from the reference dictionary. Until this integration will be completed I keep this issue open.

**Comment by simozacca** [comment]
The integration is complete and all these information are now read from the human-reference dictionary.
