### ISSUE TITLE
Lacking column names in intermediate files

### ISSUE THREAD

**Issue by ivanov-v-v** [raphael-group/chisel#8]
Dear Simone, 

I've noticed that individual files (like `baf.tsv`, `combo.tsv` etc) lack column names.
This makes it considerably harder to understand and use those intermediate results. 
Would be great to see this small feature included in the forthcoming release.

**Comment by simozacca** [comment]
There is indeed a missing header in few intermediate files and I will keep this issue open until these will be fixed.

**Comment by simozacca** [comment]
Headers have been added to temporary files and changes will take effect in the next release in bioconda.
